/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 1;
  /** RegularExpression Id. */
  int SC = 2;
  /** RegularExpression Id. */
  int EOL = 3;
  /** RegularExpression Id. */
  int PLUS = 4;
  /** RegularExpression Id. */
  int MUL = 5;
  /** RegularExpression Id. */
  int S = 6;
  /** RegularExpression Id. */
  int DEF = 7;
  /** RegularExpression Id. */
  int LCB = 8;
  /** RegularExpression Id. */
  int RCB = 9;
  /** RegularExpression Id. */
  int LPB = 10;
  /** RegularExpression Id. */
  int RPB = 11;
  /** RegularExpression Id. */
  int FNAME = 12;
  /** RegularExpression Id. */
  int PARAM = 13;
  /** RegularExpression Id. */
  int DIGITS = 14;
  /** RegularExpression Id. */
  int UPPER = 15;
  /** RegularExpression Id. */
  int LOWER = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"MAIN\"",
    "\";\"",
    "\"\\n\"",
    "\"+\"",
    "\"*\"",
    "\" \"",
    "\"DEF\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "<FNAME>",
    "<PARAM>",
    "<DIGITS>",
    "<UPPER>",
    "<LOWER>",
    "<DIGIT>",
  };

}
